### ISSUE TITLE
请帮支持laravel 7

### ISSUE THREAD

**Issue by running8gubin** [HyanCat/aliyun-direct-mail#3]
我一直使用您这个包，现在升级安装。麻烦您抽空比例支持一下laravel 7。十分感谢。

**Comment by HyanCat** [comment]
> 我一直使用您这个包，现在升级安装。麻烦您抽空比例支持一下laravel 7。十分感谢。

现在 Laravel 版本太快了😂。。我这两天抽空看看，如果你项目着急升级的话，可以自己 fork 改下，或者看看其他开发者的包。
